#!/bin/sh

case "$1" in
    start)
        # create DNS soft link
        ln -sf /run/NetworkManager/resolv.conf /etc/resolv.conf
        # Welcome splash: see S90mac6100_bootsplash (SD /mnt/Bootlogo override)
        ;;
    stop)
        # Power-off splash reserved (S90mac6100_bootsplash stop)
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
